### PR TITLE
feat: add Nix flake

### PR DESCRIPTION
**Pull request by kiike**
This PR adds a flake for Nix users. I have been using it on NixOS for a couple days when developing. It lets me avoid having a virtualenv, or even having the dev tools installed globally. Feature-wise, it's on par with the Papis one, except for the container stuff, which is not implemented yet. It might be a nice-to-have in the future though!

### CODE REVIEW

**Comment by alexfikl** [comment]
Nice! I'm fine with merging this as is and people can improve it as they see fit. 

Let me know when you think it's good to go.

**Comment by kiike** [comment]
Will do! I'm checking compatibility with the main Papis flake.

**Comment by kiike** [comment]
Good to go, @alexfikl, I added some instructions that might come in handy for Nix users :smile:.

**Comment by alexfikl** [comment]
@kiike I'm really sorry, this completely flew under my radar! Feel free to ping again in the future if we don't respond :grin:

**Comment by kiike** [comment]
That's alright. I forgot about it too :smile:

**Pull request merged**
