### PR TITLE
Update codebase

### PR DESCRIPTION
**Pull request by alexfikl**
The commits are fairly atomic, but this mostly:
* adds and fixes more `flake8` checks
* adds `mypy` and type annotations.
* updates the readme a bit
* other small updates throughout the code.

I plan to make some more pull requests after this to add more tests and makes sure everything works with the latest Zotero.

### CODE REVIEW

**Comment by alexfikl** [comment]
@alejandrogallo I don't have access to this repo, so can't merge this. What do you think about getting it in? 

The diff is a bit big because there's a lot of flake8 and mypy fixes in there, but otherwise only [3ec7ee3](https://github.com/papis/papis-zotero/pull/18/commits/3ec7ee3c811b432ae24ca8af6357cf6208cb57bb) has some proper changes (I can make a new PR for that if you want)

**Comment by alejandrogallo** [comment]
Hi alex! Thanks so much for these most needed updates, I just added you to the zotero team, feel free to do as you deem fit!

**Comment by alejandrogallo** [comment]
Should I then update to v0.2?

**Comment by alexfikl** [comment]
> Hi alex! Thanks so much for these most needed updates, I just added you to the zotero team, feel free to do as you deem fit!

Awesome! Thank you very much! I'll give it another look and merge it :rocket: 

It doesn't have any new features or bumped dependencies or anything, so I don't think a new release is worth it. I'll look through the bug reports a bit and try to add some more tests, as time permits, and bug you for a release later :grin:

**Pull request merged**
